name: bloc_ecommerce
description: "A ecommerce app using bloc state management & firebase backend"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  cloud_firestore: ^5.6.9
  equatable: ^2.0.7
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  gap: ^3.0.1
  go_router: ^13.2.0
  google_sign_in: ^6.3.0
  loading_animation_widget: ^1.3.0
  meta: ^1.11.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  shimmer_animation: ^2.2.2
  social_login_buttons: ^1.0.7
#  twitter_login: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
